import "@/utils/init";
import "app/css/build.css";
import "app/lib/event";
export { success } from "app/lib/toast";
export { HeaderTitled } from "app/comps/HeaderTitled";
import { lang } from "lib/lang";
export * from "@/exports";
export { icon } from "app/lib/icon";
export { layoutStyle } from "app/lib/layout-style";
export { session } from "app/lib/session";
await lang.init("id");
